- hosts: localhost

  tasks:
    - include: playbooks/install_packages.yml
    - include: playbooks/git_configure.yml
    - include: playbooks/ssh_keygen.yml
    - include: playbooks/updating_bashrc.yml
    - include: playbooks/install_vagrant.yml