    - name: Cloning rbenv
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: ~/.rbenv
        accept_hostkey: true
        clone: yes
        force: yes

    - name: Cloning ruby-build
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build
        accept_hostkey: true
        clone: yes
        force: yes
        
    - name: Cloning rbenv-gemset
      git:
        repo: https://github.com/jf/rbenv-gemset
        dest: ~/.rbenv/plugins/rbenv-gemset
        accept_hostkey: true
        clone: yes
        force: yes

    - name: Set PATH for rbenv
      lineinfile:
        dest: '~/.bashrc'
        line: '{{ item }}'
        state: present
        create: yes
      with_items:
        - export PATH="$HOME/.rbenv/bin:$PATH"
        - eval "$(rbenv init -)"
