    - name: Add ppa sources
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - 'ppa:webupd8team/sublime-text-3'
        - 'ppa:numix/ppa'
      become: yes

    - name: Install packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - build-essential
        - wget
        - curl
        - nvidia-352-updates
        - sublime-text-installer
        - numix-icon-theme-circle
        - git
        - git-flow
        - mc
        - unity-tweak-tool
      become: yes

