    - name: update .bashrc
      lineinfile:
        dest: '~/.bashrc'
        line: '{{ item }}'
        state: present
        create: yes
      with_items:
        - PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\w\a\]\u@\h \w\$(__git_ps1 "[%s]")\n:$ "
        - eval "$(ssh-agent -s)" > /dev/null 2>&1
        - ssh-add ~/.ssh/id_rsa > /dev/null 2>&1
        